In [430]:
!pip install anndata

Requirement already satisfied: anndata in /usr/local/lib/python3.12/dist-packages (0.12.11)
Requirement already satisfied: array-api-compat>=1.7.1 in /usr/local/lib/python3.12/dist-packages (from anndata) (1.14.0)
Requirement already satisfied: h5py>=3.8 in /usr/local/lib/python3.12/dist-packages (from anndata) (3.16.0)
Requirement already satisfied: legacy-api-wrap in /usr/local/lib/python3.12/dist-packages (from anndata) (1.5)
Requirement already satisfied: natsort in /usr/local/lib/python3.12/dist-packages (from anndata) (8.4.0)
Requirement already satisfied: numpy>=1.26 in /usr/local/lib/python3.12/dist-packages (from anndata) (2.0.2)
Requirement already satisfied: packaging>=24.2 in /usr/local/lib/python3.12/dist-packages (from anndata) (26.1)
Requirement already satisfied: pandas!=2.1.2,<3,>=2.1.0 in /usr/local/lib/python3.12/dist-packages (from anndata) (2.2.2)
Requirement already satisfied: scipy!=1.17.0,>=1.12 in /usr/local/lib/python3.12/dist-packages (from anndata) (1.16.3)
Requirement already satisfied: scverse-misc>=0.0.3 in /usr/local/lib/python3.12/dist-packages (from anndata) (0.0.4)
Requirement already satisfied: zarr!=3.0.*,>=2.18.7 in /usr/local/lib/python3.12/dist-packages (from anndata) (3.1.6)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas!=2.1.2,<3,>=2.1.0->anndata) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas!=2.1.2,<3,>=2.1.0->anndata) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas!=2.1.2,<3,>=2.1.0->anndata) (2026.1)
Requirement already satisfied: session-info2 in /usr/local/lib/python3.12/dist-packages (from scverse-misc>=0.0.3->anndata) (0.4.1)
Requirement already satisfied: typing-extensions in /usr/local/lib/python3.12/dist-packages (from scverse-misc>=0.0.3->anndata) (4.15.0)
Requirement already satisfied: donfig>=0.8 in /usr/local/lib/python3.12/dist-packages (from zarr!=3.0.*,>=2.18.7->anndata) (0.8.1.post1)
Requirement already satisfied: google-crc32c>=1.5 in /usr/local/lib/python3.12/dist-packages (from zarr!=3.0.*,>=2.18.7->anndata) (1.8.0)
Requirement already satisfied: numcodecs>=0.14 in /usr/local/lib/python3.12/dist-packages (from zarr!=3.0.*,>=2.18.7->anndata) (0.16.5)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.12/dist-packages (from donfig>=0.8->zarr!=3.0.*,>=2.18.7->anndata) (6.0.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas!=2.1.2,<3,>=2.1.0->anndata) (1.17.0)

In [431]:
import numpy as np
import pandas as pd
import anndata as ad
from scipy.sparse import csr_matrix
print(ad.__version__)

0.12.11

/tmp/ipykernel_6544/2319192822.py:5: FutureWarning: `__version__` is deprecated, use `importlib.metadata.version('anndata')` instead.
  print(ad.__version__)

In [432]:
# Initializing AnnData
counts = csr_matrix(np.random.poisson(1, size=(100, 2000)), dtype=np.float32)
adata = ad.AnnData(counts)
adata

adata.X

adata.obs_names = [f"Cell_{i:d}" for i in range(adata.n_obs)]
adata.var_names = [f"Gene_{i:d}" for i in range(adata.n_vars)]
print(adata.obs_names[:10])

Index(['Cell_0', 'Cell_1', 'Cell_2', 'Cell_3', 'Cell_4', 'Cell_5', 'Cell_6',
       'Cell_7', 'Cell_8', 'Cell_9'],
      dtype='object')

In [433]:
# Subsetting AnnData
adata[["Cell_1", "Cell_10"], ["Gene_5", "Gene_1900"]]

View of AnnData object with n_obs × n_vars = 2 × 2

In [434]:
# Adding aligned metadata
ct = np.random.choice(["B", "T", "Monocyte"], size=(adata.n_obs,))
adata.obs["cell_type"] = pd.Categorical(ct)  # Categoricals are preferred for efficiency
adata.obs

        cell_type
Cell_0   Monocyte
Cell_1          B
Cell_2          B
Cell_3          T
Cell_4          T
...           ...
Cell_95         T
Cell_96  Monocyte
Cell_97  Monocyte
Cell_98  Monocyte
Cell_99         T

[100 rows x 1 columns]

In [435]:
adata

AnnData object with n_obs × n_vars = 100 × 2000
    obs: 'cell_type'

In [436]:
#  Subsetting using metadata
bdata = adata[adata.obs.cell_type == "B"]
bdata

View of AnnData object with n_obs × n_vars = 34 × 2000
    obs: 'cell_type'

In [437]:
# Observation/variable-level matrices
adata.obsm["X_umap"] = np.random.normal(0, 1, size=(adata.n_obs, 2))
adata.varm["gene_stuff"] = np.random.normal(0, 1, size=(adata.n_vars, 5))
adata.obsm

AxisArrays with keys: X_umap

In [438]:
adata

AnnData object with n_obs × n_vars = 100 × 2000
    obs: 'cell_type'
    obsm: 'X_umap'
    varm: 'gene_stuff'

In [439]:
# Unstructured metadata
adata.uns["random"] = [1, 2, 3]
adata.uns

OrderedDict([('random', [1, 2, 3])])

In [440]:
#  Layers
adata.layers["log_transformed"] = np.log1p(adata.X)
adata

AnnData object with n_obs × n_vars = 100 × 2000
    obs: 'cell_type'
    uns: 'random'
    obsm: 'X_umap'
    varm: 'gene_stuff'
    layers: 'log_transformed'

In [441]:
# Conversion to DataFrames
adata.to_df(layer="log_transformed")

,Gene_0,Gene_1,Gene_2,Gene_3,Gene_4,Gene_5,Gene_6,Gene_7,Gene_8,Gene_9,...,Gene_1990,Gene_1991,Gene_1992,Gene_1993,Gene_1994,Gene_1995,Gene_1996,Gene_1997,Gene_1998,Gene_1999
Cell_0,0.693147,1.098612,0.693147,0.693147,1.098612,0.000000,1.098612,0.000000,0.000000,0.000000,...,0.000000,0.693147,0.000000,0.000000,0.000000,0.693147,1.098612,0.693147,0.693147,1.098612
Cell_1,0.693147,0.000000,0.693147,0.000000,0.000000,0.693147,0.000000,0.693147,0.693147,0.693147,...,0.000000,1.098612,0.000000,0.000000,1.098612,0.693147,0.000000,0.000000,0.000000,0.000000
Cell_2,0.000000,1.098612,0.000000,1.386294,0.000000,1.098612,1.609438,0.693147,0.000000,0.693147,...,0.693147,0.693147,0.693147,0.693147,0.000000,0.693147,0.693147,0.000000,0.000000,0.000000
Cell_3,0.000000,0.000000,1.098612,1.098612,0.693147,0.693147,0.693147,1.098612,1.098612,0.693147,...,0.693147,0.693147,1.098612,0.693147,1.098612,1.098612,0.000000,1.386294,0.000000,0.693147
Cell_4,0.693147,0.693147,1.609438,0.693147,0.693147,0.693147,0.693147,1.098612,0.000000,0.000000,...,0.693147,0.000000,1.386294,0.693147,0.000000,1.098612,0.693147,1.098612,1.098612,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Cell_95,1.098612,1.098612,1.098612,0.693147,0.693147,0.693147,1.098612,0.693147,0.000000,0.693147,...,0.000000,0.693147,0.000000,1.386294,0.000000,0.693147,0.000000,1.098612,0.000000,1.098612
Cell_96,1.098612,1.386294,0.693147,0.000000,0.000000,1.386294,1.386294,0.693147,0.000000,0.000000,...,0.000000,0.000000,0.693147,0.000000,0.000000,0.000000,0.000000,1.609438,0.000000,1.791759
Cell_97,1.098612,1.098612,0.693147,0.000000,0.000000,0.693147,1.098612,0.000000,0.000000,1.098612,...,1.386294,0.000000,0.693147,0.000000,0.693147,0.693147,0.000000,0.693147,0.693147,0.000000
Cell_98,0.000000,0.000000,0.693147,1.386294,0.693147,0.000000,0.000000,0.693147,0.693147,0.693147,...,0.000000,0.000000,1.098612,0.693147,0.000000,0.000000,0.693147,0.693147,1.098612,0.693147
Cell_99,0.693147,1.098612,1.098612,0.000000,0.000000,0.693147,0.000000,0.693147,0.000000,0.000000,...,0.000000,0.693147,0.693147,1.098612,1.098612,0.693147,1.386294,1.386294,1.098612,1.098612

In [442]:
#  Writing the results to disk
adata.write('my_results.h5ad', compression="gzip")

In [443]:
!ls -lh my_results.h5ad

-rw-r--r-- 1 root root 661K Apr 28 13:06 my_results.h5ad

In [444]:
# Views and copies
obs_meta = pd.DataFrame({
        'time_yr': np.random.choice([0, 2, 4, 8], adata.n_obs),
        'subject_id': np.random.choice(['subject 1', 'subject 2', 'subject 4', 'subject 8'], adata.n_obs),
        'instrument_type': np.random.choice(['type a', 'type b'], adata.n_obs),
        'site': np.random.choice(['site x', 'site y'], adata.n_obs),
    },
    index=adata.obs.index,    # these are the same IDs of observations as above!
)

In [445]:
adata = ad.AnnData(adata.X, obs=obs_meta, var=adata.var)
print(adata)

AnnData object with n_obs × n_vars = 100 × 2000
    obs: 'time_yr', 'subject_id', 'instrument_type', 'site'

In [446]:
adata[:5, ['Gene_1', 'Gene_3']]

View of AnnData object with n_obs × n_vars = 5 × 2
    obs: 'time_yr', 'subject_id', 'instrument_type', 'site'

In [447]:
adata_subset = adata[:5, ['Gene_1', 'Gene_3']].copy()

In [448]:
print(adata[:3, 'Gene_1'].X.toarray().tolist())
adata[:3, 'Gene_1'].X = [0, 0, 0]
print(adata[:3, 'Gene_1'].X.toarray().tolist())

[[2.0], [0.0], [2.0]]
[[0.0], [0.0], [0.0]]

/usr/local/lib/python3.12/dist-packages/anndata/_core/anndata.py:639: FutureWarning: Setting element `.X` of view of `AnnData` object will obey copy-on-write semantics in the next minor release.
  if self._handle_view_X_cow(value):
/tmp/ipykernel_6544/2822107891.py:2: ImplicitModificationWarning: Modifying `X` on a view results in data being overridden
  adata[:3, 'Gene_1'].X = [0, 0, 0]

In [449]:
adata_subset = adata[:3, ['Gene_1', 'Gene_2']]

In [450]:
adata_subset

View of AnnData object with n_obs × n_vars = 3 × 2
    obs: 'time_yr', 'subject_id', 'instrument_type', 'site'

In [451]:
adata_subset.obs['foo'] = range(3)

/tmp/ipykernel_6544/2955902014.py:1: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  adata_subset.obs['foo'] = range(3)

In [452]:
adata[adata.obs.time_yr.isin([2, 4])].obs.head()

         time_yr subject_id instrument_type    site
Cell_3         2  subject 1          type a  site y
Cell_4         2  subject 1          type a  site y
Cell_7         4  subject 4          type a  site x
Cell_9         2  subject 8          type b  site x
Cell_10        4  subject 2          type b  site y

In [453]:
adata.file.close()